sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache/files
  environment:
    elasticsearch: false
    redis: false
    postgresql: false

matrix:
    include:
        - php: 7.1
        - php: 7.2
          env: deps=low
    fast_finish: true

before_script:
  - phpenv config-rm xdebug.ini
  - if [[ $deps = low ]]; then make update-min; else make install; fi

script:
  - if [[ $deps = low ]]; then make test-min; else make test; fi
